### ISSUE TITLE
Pass micromanagerroot as option

### ISSUE THREAD

**Issue by shelldandy** [estrattonbailey/micromanager#2]
https://github.com/estrattonbailey/micromanager/blob/045f623f44d4963c69ffa574a993e91dac3d428c/package/index.js#L24

So there's no need to setup aliases on webpack and babel.

Something along the lines of `scripts.mount({micromanagerRoot: './components'})`

And your end it could have the default of

`export function mount ({micromanagerRoot: 'micromanagerRoot'}) {`

So it can be backwards compatible??

🤔 

Thoughts?

**Comment by estrattonbailey** [comment]
Hey thanks for the contribution! I think #3 looks good, happy to publish.

Would you mind adding a note to the README?

**Comment by estrattonbailey** [comment]
@shelldandy published `v1.1.0`.

Related, I've recently worked on a [simpler version of this idea](https://github.com/estrattonbailey/picoapp) (still need to finish those docs, my bad). Might be of interest to you! Or an alternative: [data-components](https://github.com/rafaelrinaldi/data-components).

**Comment by shelldandy** [comment]
That's amazing! I'll add the note. and pr again

**Comment by shelldandy** [comment]
#4

**Comment by shelldandy** [comment]
@estrattonbailey that picoapp looks really cool! although i really like from this package is that it auto-mounts all the things (i guess i could write a thing for that on my app as well) 🤔 

I'll give it a spin, since i'm really liking the concept of this style of apps + pjax.

I'm wondering if you've experimented with HMR and these apps, potentially doable right?

**Comment by estrattonbailey** [comment]
@shelldandy picapp does the same, basically. But yeah, it's a neat pattern, def helpful for pjax use cases. That's actually what pushed me to write this library.

HMR, I haven't using this pattern. But I imagine you could expose a sort-of `dispose` method from modules and then cycle through the module cache on `accept()` and run the `dispose` methods etc. Honestly I usually opt for live-reloading so that I don't have to mess with HMR 😝

**Comment by shelldandy** [comment]
fair point, i also opt out of HMR for non framework JS code because it is messy.

Well thanks a lot for the conversation! I'll experiment with both libs and let you know whats up.

I'll close this now
